GET http://localhost:8000/bears

###

GET http://localhost:8000/bears/6991461eea836f2c39d780f9

###

POST http://localhost:8000/bears
Content-Type: application/json

{
    "name": "Beary",
    "breed": "Polar",
    "gender": "Female"
}

###

DELETE http://localhost:8000/bears/6991461eea836f2c39d780f9

###

PATCH http://localhost:8000/bears/6991457eea836f2c39d780f7
Content-Type: application/json

{
    "name": "New Bear",
    "breed": "New Breed",
    "gender": "New Gender"
} 